CITY_MAP = {
    "Tallinn": {"yrno": "Harjumaa/Tallinn", "emhi": "784"},
    "Tartu": {"yrno": "Tartumaa/Tartu", "emhi": "795"},
    "Narva": {"yrno": "Ida-Virumaa/Narva", "emhi": "511"},
    "Pärnu": {"yrno": "Pärnumaa/Pärnu", "emhi": "625"},
    "Kohtla-Järve": {"yrno": "Ida-Virumaa/Kohtla-Järve", "emhi": "322"},
    "Viljandi": {"yrno": "Viljandimaa/Viljandi", "emhi": "897"},
    "Maardu": {"yrno": "Harjumaa/Maardu", "emhi": "4704"},
    "Rakvere": {"yrno": "Lääne-Virumaa/Rakvere", "emhi": "663"},
    "Sillamäe": {"yrno": "Ida-Virumaa/Sillamäe", "emhi": "735"},
    "Võru": {"yrno": "Võrumaa/Võru", "emhi": "919"},
    "Kuressaare": {"yrno": "Saaremaa/Kuressaare", "emhi": "349"},
    "Valga": {"yrno": "Valgamaa/Valga", "emhi": "854"},
    "Jõhvi": {"yrno": "Ida-Virumaa/Jõhvi", "emhi": "2270"},
    "Haapsalu": {"yrno": "Läänemaa/Haapsalu", "emhi": "183"},
    "Keila": {"yrno": "Harjumaa/Keila", "emhi": "296"},
    "Paide": {"yrno": "Järvamaa/Paide", "emhi": "566"},
    "Türi": {"yrno": "Järvamaa/Türi", "emhi": "8595"},
    "Tapa": {"yrno": "Lääne-Virumaa/Tapa", "emhi": "8140"},
    "Põlva": {"yrno": "Põlvamaa/Põlva", "emhi": "620"},
    "Kiviõli": {"yrno": "Ida-Virumaa/Kiviõli", "emhi": "309"},
    "Elva": {"yrno": "Tartumaa/Elva", "emhi": "170"},
    "Saue": {"yrno": "Harjumaa/Saue", "emhi": "728"},
    "Jõgeva": {"yrno": "Jõgevamaa/Jõgeva", "emhi": "249"},
    "Rapla": {"yrno": "Raplamaa/Rapla", "emhi": "6826"},
    "Põltsamaa": {"yrno": "Jõgevamaa/Põltsamaa", "emhi": "617"},
    "Paldiski": {"yrno": "Harjumaa/Paldiski", "emhi": "580"},
    "Sindi": {"yrno": "Pärnumaa/Sindi", "emhi": "741"},
    "Kunda": {"yrno": "Lääne-Virumaa/Kunda", "emhi": "3610"},
    "Kärdla": {"yrno": "Hiiumaa/Kärdla", "emhi": "371"},
    "Kehra": {"yrno": "Harjumaa/Kehra", "emhi": "2925"},
    "Loksa": {"yrno": "Harjumaa/Loksa", "emhi": "424"},
    "Räpina": {"yrno": "Põlvamaa/Räpina", "emhi": "7216"},
    "Tõrva": {"yrno": "Valgamaa/Tõrva", "emhi": "823"},
    "Narva-Jõesuu": {"yrno": "Ida-Virumaa/Narva-Jõesuu", "emhi": "513"},
    "Tamsalu": {"yrno": "Lääne-Virumaa/Tamsalu", "emhi": "8130"},
    "Otepää": {"yrno": "Valgamaa/Otepää", "emhi": "5754"},
    "Kilingi-Nõmme": {"yrno": "Pärnumaa/Kilingi-Nõmme", "emhi": "3083"},
    "Karksi-Nuia": {"yrno": "Viljandimaa/Karksi-Nuia", "emhi": "2761"},
    "Lihula": {"yrno": "Läänemaa/Lihula", "emhi": "4330"},
    "Mustvee": {"yrno": "Jõgevamaa/Mustvee", "emhi": "485"},
    "Võhma": {"yrno": "Viljandimaa/Võhma", "emhi": "912"},
    "Antsla": {"yrno": "Võrumaa/Antsla", "emhi": "1301"},
    "Abja-Paluoja": {"yrno": "Viljandimaa/Abja-Paluoja", "emhi": "1060"},
    "Püssi": {"yrno": "Ida-Virumaa/Püssi", "emhi": "645"},
    "Suure-Jaani": {"yrno": "Viljandimaa/Suure-Jaani", "emhi": "7836"},
    "Kallaste": {"yrno": "Tartumaa/Kallaste", "emhi": "279"}
}

ELEMENTS_MAP = {
    "emhi": {
        "precipitation": "value",
        "temperature": "value",
        "pressure": "value",
        "phenomen": "className",
        "windDirection": "deg",
        "windSpeed": "mps"
    },
    "yrno": {
        "precipitation": "value",
        "temperature": "value",
        "pressure": "value",
        "symbol": "var",
        "windDirection": "deg",
        "windSpeed": "mps"
    },
    "emhi_symbols": {
        "clear": "01d",
        "few_clouds": "02d",
        "variable_clouds": "03d",
        "cloudy_with_clear_spells": "03d",
        "cloudy": "04",
        "light_shower": "40d",
        "moderate_shower": "05d",
        "heavy_shower": "41d",
        "light_rain": "46",
        "moderate_rain": "09",
        "heavy_rain": "10",
        "thunder": "22",
        "thunder_storm": "11",
        "light_sleet": "42d",
        "moderate_sleet": "43d",
        "light_snowfall": "49",
        "moderate_snowfall": "13",
        "heavy_snowfall": "50",
        "snowstorm": "50",
        "light_snow_shower": "44d",
        "moderate_snow_shower": "08d",
        "heavy_snow_shower": "45d",
        "hail": "49",
        "fog": "15",
        "mist": "15",
        "drifting_snow": "15",
        "risk_of_glaze": "15"
    }
}
